apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: webapp-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/deployment-of-youtube-main'
    targetRevision: HEAD
    path: helm-gitops-project/charts/webapp
    helm:
      valueFiles:
      - values/dev.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
