deploymentName: webapp-dev
namespace: dev
environment: development
port: 80
replicaCount: 1
image:
  repository: 020880439519.dkr.ecr.eu-north-1.amazonaws.com/youtube2.0
  tag: latest
  pullPolicy: Always
service:
  type: ClusterIP
  port: 80
# Simple ingress config without domain

ingress:
  enabled: true
  className: nginx
  path: /webapp-dev
  hostnames:
  - dev-webapp.local
  annotations: {}
  addRootPath: true # Only add this to one of your environments (prod or dev)
resources:
  requests:
    memory: "64Mi"
    cpu: "50m"
  limits:
    memory: "128Mi"
    cpu: "100m"

#
